import { toEmbedded } from "./corpus.js";
import type { CorpusCase } from "./corpus.js";

/**
 * Hand-written cases for rules whose *entire* mechanically-derived corpus contribution is
 * excluded (every documented example either fails to parse standalone, per
 * `isValidStandaloneGraphQL`, or needs schema/document plumbing graphql-eslint's own docs don't
 * provide) — see conformance.test.ts's "coverage audit" for the mechanically-computed list this
 * is checked against.
 *
 * Deliberately kept separate from `buildCorpus()` (mechanically derived straight from
 * `@graphql-eslint/eslint-plugin`'s own `meta.docs.examples`) rather than folded in: this file's
 * content is authored by hand, so mixing it into the derived corpus would make the corpus's
 * "these are the rule's own documented examples" claim false. `conformance.test.ts` runs and
 * reports these in a separate describe block with a separate table, never combined into the
 * derived corpus's counts.
 *
 * Each entry documents which real-world condition it's demonstrating, since (unlike the derived
 * corpus) there's no upstream doc example to point to for justification.
 */
export function buildSupplementalCorpus(): CorpusCase[] {
  return [
    {
      ruleId: "no-anonymous-operations",
      caseId: "no-anonymous-operations-supplemental-0",
      title: "Supplemental (anonymous query)",
      options: [],
      rawCode: "query {\n  user(id: \"1\") {\n    id\n  }\n}",
      code: toEmbedded("query {\n  user(id: \"1\") {\n    id\n  }\n}"),
    },
    {
      ruleId: "description-style",
      caseId: "description-style-supplemental-0",
      title: "Supplemental (block description with style: inline)",
      options: [{ style: "inline" }],
      rawCode: '""" Description """\ntype SomeType {\n  id: ID!\n}',
      code: toEmbedded('""" Description """\ntype SomeType {\n  id: ID!\n}'),
    },
    {
      // Needs the shared conformance schema's Mutation.renameUser field (see
      // fixtures/schema.graphql), which returns RenameUserPayload — a type with no field of
      // type Query, unlike CreateUserPayload (whose `user`/`query` shape is what the rule's own
      // "Correct" example, excluded as unparsable standalone GraphQL, was illustrating).
      ruleId: "require-field-of-type-query-in-mutation-result",
      caseId: "require-field-of-type-query-in-mutation-result-supplemental-0",
      title: "Supplemental (mutation result missing a Query-typed field)",
      options: [],
      rawCode: "type Mutation {\n  renameUser: RenameUserPayload!\n}",
      code: toEmbedded("type Mutation {\n  renameUser: RenameUserPayload!\n}"),
    },
    {
      ruleId: "require-type-pattern-with-oneof",
      caseId: "require-type-pattern-with-oneof-supplemental-0",
      title: "Supplemental (@oneOf type missing the error field)",
      options: [],
      rawCode: "type BadResult @oneOf {\n  ok: String\n}",
      code: toEmbedded("type BadResult @oneOf {\n  ok: String\n}"),
    },
    // Coverage gap A from the final review: the 27 "graphql-js-validation" rules (thin wrappers
    // generated by rules/graphql-js-validation.js around a graphql-js validation function; see
    // that file) share one implementation with its own code path -- distinct from every other
    // rule in this plugin -- and none of it was previously exercised by any test: token
    // scanning (`tokens.find(t => t.loc.start.line === line && ...)`), passing a raw token's
    // `loc` straight through to `context.report`, and (for the "did you mean" subset)
    // `fixer.replaceText(token, name)` for a suggestion's fix. All 27 have zero
    // `meta.docs.examples` upstream (see EXPECTED_ZERO_EXAMPLE_RULE_IDS in
    // conformance.test.ts), so none of them ever contributes a derived-corpus case -- this is
    // exactly the situation the supplemental-corpus mechanism exists for (see the four cases
    // above), not a gap this mechanism structurally can't fill. Three cases below, each chosen
    // to exercise a genuinely different shape of that shared code path rather than three
    // near-duplicates of the same one:
    {
      // Shape 1: exercises `fixer.replaceText(token, name)` (the suggestion-fix half of the
      // shared implementation) — the diagnostics comparison here only asserts line/column/
      // message equality (normalize.ts doesn't compare `suggestions` at all), so what this case
      // proves through the conformance run is that building the suggestion doesn't throw and
      // the surrounding diagnostic still lines up; the suggestion's own fix was separately
      // verified by hand against the real CLI (`--fix-suggestions` renames `naem` to `name`,
      // byte for byte). Chosen over the other `hasDidYouMeanSuggestions` rules in this family
      // (known-argument-names, known-type-names, scalar-leafs, value-literals-of-correct-type,
      // possible-type-extension) because a misspelled field name is the most common real-world
      // trigger for this rule.
      ruleId: "fields-on-correct-type",
      caseId: "fields-on-correct-type-supplemental-0",
      title: "Supplemental (misspelled field name, exercises the Did-you-mean suggestion/fix)",
      options: [],
      rawCode: "query GetUser {\n  user(id: \"1\") {\n    naem\n  }\n}",
      code: toEmbedded("query GetUser {\n  user(id: \"1\") {\n    naem\n  }\n}"),
    },
    {
      // Shape 2: a rule with NO suggestions (plain token-loc-only report, no `fixer` call at
      // all) and, unlike every other case in this file, one with genuinely zero documented
      // examples upstream for ANY reason -- not merely all-excluded. Also routes through
      // `handleMissingFragments` (this rule's `getDocumentNode`), taking its early-return branch
      // (`missingFragments.length === 0`, no `...FragmentSpread` present) rather than the
      // `requireGraphQLOperations`-throwing branch already covered by the derived corpus's other
      // conditional-`documents` rules (known-fragment-names) -- a second, distinct path through
      // that shared helper.
      ruleId: "no-undefined-variables",
      caseId: "no-undefined-variables-supplemental-0",
      title: "Supplemental (undefined variable, plain token-loc report with no suggestion)",
      options: [],
      rawCode: "query GetUser {\n  user(id: $userId) {\n    id\n  }\n}",
      code: toEmbedded("query GetUser {\n  user(id: $userId) {\n    id\n  }\n}"),
    },
    {
      // Shape 3: unlike the two cases above (each producing exactly one diagnostic), this one's
      // input is built to report on TWO distinct field selections in the same document at once
      // -- proving the shared `tokens.find(...)` per-error token lookup and `context.report`
      // loop in `validateDocument` (see graphql-js-validation.js) correctly re-finds a different
      // token for each of several errors from a single `validate()` call, not just the first.
      // Also one of the 9 rules the reviewer hand-verified directly against real ESLint before
      // filing this as a coverage gap rather than a suspected bug.
      ruleId: "overlapping-fields-can-be-merged",
      caseId: "overlapping-fields-can-be-merged-supplemental-0",
      title: "Supplemental (two independent field conflicts, two diagnostics from one validate() call)",
      options: [],
      rawCode:
        'query GetUser {\n  user(id: "1") {\n    friends(first: 5) {\n      edges { cursor }\n    }\n    friends(first: 10) {\n      edges { cursor }\n    }\n    name: id\n    name\n  }\n}',
      code: toEmbedded(
        'query GetUser {\n  user(id: "1") {\n    friends(first: 5) {\n      edges { cursor }\n    }\n    friends(first: 10) {\n      edges { cursor }\n    }\n    name: id\n    name\n  }\n}',
      ),
    },
  ];
}
